name: Update changelog

on:
  workflow_run:
    workflows: ["Update version"]
    types:
      - completed

jobs:
  update-changelog:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (master)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
          fetch-depth: 0

      - name: Get current version
        id: version
        run: |
          if [ -f version ]; then
            echo "current_version=$(cat version)" >> $GITHUB_OUTPUT
          else
            echo "Error: version file not found"
            exit 1
          fi

      - name: Get branch name
        id: branch
        run: |
          echo "branch_name=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT

      - name: Update changelog.md for master
        run: |
          CURRENT_TIME=$(date '+%H:%M')
          CURRENT_DATE=$(date '+%Y.%m.%d')
          VERSION="${{ steps.version.outputs.current_version }}"
          BRANCH="${{ steps.branch.outputs.branch_name }}"
          NEW_ENTRY="[${CURRENT_TIME} - ${CURRENT_DATE} ${VERSION} ${BRANCH}]"

          TEMP_FILE=$(mktemp)
          echo "${NEW_ENTRY}" > "${TEMP_FILE}"
          echo "---" >> "${TEMP_FILE}"
          cat changelog.md >> "${TEMP_FILE}"
          mv "${TEMP_FILE}" changelog.md
          
          git add changelog.md

      - name: Commit changes to master
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Update changelog: [${CURRENT_TIME} - ${CURRENT_DATE} ${{ steps.version.outputs.current_version }} ${{ steps.branch.outputs.branch_name }}]" || echo "No changes to commit"
          git push origin master

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Update changelog.md for PR branch
        run: |
          CURRENT_TIME=$(date '+%H:%M')
          CURRENT_DATE=$(date '+%Y.%m.%d')
          VERSION="${{ steps.version.outputs.current_version }}"
          BRANCH="${{ steps.branch.outputs.branch_name }}"
          NEW_ENTRY="[${CURRENT_TIME} - ${CURRENT_DATE} ${VERSION} ${BRANCH}]"

          TEMP_FILE=$(mktemp)
          echo "${NEW_ENTRY}" > "${TEMP_FILE}"
          echo "---" >> "${TEMP_FILE}"
          cat changelog.md >> "${TEMP_FILE}"
          mv "${TEMP_FILE}" changelog.md
          
          git add changelog.md

      - name: Commit changes to PR branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Update changelog: [${CURRENT_TIME} - ${CURRENT_DATE} ${{ steps.version.outputs.current_version }} ${{ steps.branch.outputs.branch_name }}]" || echo "No changes to commit"
          git push origin ${{ github.event.workflow_run.head_branch }}

      - name: Add changelog label
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const prs = context.payload.workflow_run.pull_requests
              if (prs && prs.length > 0) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prs[0].number,
                  labels: ['changelog']
                })
              }
            } catch (error) {
              console.log('Error adding label:', error)
            }
