name: Update changelog

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (master)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
          fetch-depth: 0

      - name: Get current version
        id: version
        run: |
          if [ -f version ]; then
            echo "current_version=$(cat version)" >> $GITHUB_OUTPUT
          else
            echo "current_version=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Get PR details
        id: pr-details
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_BRANCH=${{ github.event.pull_request.head.ref }}
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "pr_branch=$PR_BRANCH" >> $GITHUB_OUTPUT

      - name: Get commits from PR
        id: commits
        run: |
          PR_NUMBER="${{ steps.pr-details.outputs.pr_number }}"
          COMMITS_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/commits")
          COMMITS=$(echo "$COMMITS_DATA" | jq -r '.[] | "- " + .commit.message')
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update changelog.md
        run: |
          CURRENT_TIME=$(date '+%H:%M')
          CURRENT_DATE=$(date '+%Y.%m.%d')
          VERSION="${{ steps.version.outputs.current_version }}"
          BRANCH="${{ steps.pr-details.outputs.pr_branch }}"
          NEW_ENTRY="[${CURRENT_TIME} - ${CURRENT_DATE} ${VERSION} ${BRANCH}]"
          COMMITS="${{ steps.commits.outputs.commits }}"

          TEMP_FILE=$(mktemp)
          echo "" >> "${TEMP_FILE}"
          echo "${NEW_ENTRY}" >> "${TEMP_FILE}"
          echo "---" >> "${TEMP_FILE}"
          echo "${COMMITS}" >> "${TEMP_FILE}"

          if [ -f changelog.md ]; then
            echo "" >> "${TEMP_FILE}"
            cat changelog.md >> "${TEMP_FILE}"
          fi

          mv "${TEMP_FILE}" changelog.md
          git add changelog.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Update changelog for PR #${{ steps.pr-details.outputs.pr_number }} from ${{ steps.pr-details.outputs.pr_branch }}" || echo "No changes to commit"
          git push origin master
