name: Telegram notification

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  notify:
    name:  Notify in telegram
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  

    steps:
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY.MM.DD HH:mm:ss
          utcOffset: "+03:00"  

      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY

      - name: Checkout on release
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get current version
        id: version
        run: |
          echo "current_version=$(cat version)" >> $GITHUB_OUTPUT

      - name: send telegram message on PR
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          document: changelog.md
          message: |           
            <b>Новый выпуск изменений</b>
            <b>Проект</b>: <code>${{ github.event.repository.name }}</code>
            <b>Версия</b>: <code>${{ steps.version.outputs.current_version }}</code>
            <b>Дата</b>: <code>${{ steps.current-time.outputs.formattedTime }}</code>
            <b>Автор</b>: <a href="https://github.com/${{ github.event.pull_request.user.login }}">${{ github.event.pull_request.user.login }}</a>
            <b>Описание изменений:</b> ${{ github.event.pull_request.title }}

            <b>Информация о Git-репозитории</b>
            <b>GIT MR</b>: <a href="${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}">${{ github.event.pull_request.number }}</a>
            <b>GIT TAG</b>: <a href="${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.version.outputs.current_version }}">${{ steps.version.outputs.current_version }}</a>
            
            <b>Информация о Docker-репозитории</b>
            <b>Владелец</b>: <a href="https://hub.docker.com/repositories/${{ secrets.DOCKER_USERNAME }}">${{ secrets.DOCKER_USERNAME }}</a>
            <b>Название</b>: <a href="https://hub.docker.com/repository/docker/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}/general">${{ github.event.repository.name }}</a>
            <b>Тег</b>: <a href="https://hub.docker.com/repository/docker/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}/tags">${{ steps.version.outputs.current_version }}</a>
            <b>Полное имя</b>: <a href="https://hub.docker.com/repository/docker/${{ secrets.DOCKERHUB_LOGIN }}/${{ github.event.repository.name }}/tags">Pipeline:v${{ steps.version.outputs.current_version }}</a>

env:
  REPO_NAME: ${{ github.event.repository.name }}
  CHANGELOG_FILE: changelog.md
  PR_NUMBER: ${{ github.event.pull_request.number }}
  URL_REPO: ${{ github.server_url }}/${{ github.repository }}
