name: Update changelog

on:
  workflow_run:
    workflows: ["Update version"]
    types:
      - completed

jobs:
  update-changelog:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Reading current version
        id: version
        run: |
          if [ -f version ]; then
            CURRENT_VERSION=$(cat version)
            echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Error: version file is not found"
            exit 1
          fi

      - name: Getting info about branch
        id: branch
        run: |
          if [ -z "${{ github.event.workflow_run.head_branch }}" ]; then
            echo "Error: Couldn't define branch"
            exit 1
          fi
          echo "branch_name=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT

      - name: Updating changelog.md
        run: |
          NEW_VERSION=${{ steps.version.outputs.current_version }}
          BRANCH="${{ steps.branch.outputs.branch_name }}"
          
          # Формируем новую запись с переносом строки
          NEW_ENTRY="$NEW_VERSION - $BRANCH\n"
          
          # Если файл существует, читаем его и добавляем новую запись в начало
          if [ -f changelog.md ]; then
            # Удаляем лишние пустые строки в начале и конце существующего содержимого
            EXISTING_CONTENT=$(cat changelog.md | sed -e '${/^$/d;}' | sed -e '1{/^$/d;}')
            echo -e "${NEW_ENTRY}${EXISTING_CONTENT}" > changelog.md
          else
            # Создаем новый файл
            echo -e "${NEW_ENTRY}" > changelog.md
          fi
          
          git add changelog.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Update changelog: ${{ steps.version.outputs.current_version }} - ${{ steps.branch.outputs.branch_name }}"
          git push origin ${{ github.event.workflow_run.head_branch }}

      - name: Add changelog label to PR
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const prs = context.payload.workflow_run.pull_requests
              if (prs && prs.length > 0) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prs[0].number,
                  labels: ['changelog']
                })
              }
            } catch (error) {
              console.log('Label adding error:', error)
            }
