name: Update version

on:
  pull_request:
    types: [closed]  
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master 
          fetch-depth: 0  

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: What type of update
        id: update-type
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" =~ "feature" ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif [[ "$PR_TITLE" =~ "hotfix" ]]; then
            echo "type=patch" >> $GITHUB_OUTPUT
          else
            echo "Error: No hotfix or feature in PR title."
            exit 1  
          fi

      - name: Saving old version
        id: old-version
        run: |
          OLD_VERSION=$(cat version)
          echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
      
      - name: Update version
        run: |
          echo "${{ steps.update-type.outputs.type }}" | python version_up.py

      - name: Get new version and temporary 
        id: new-version
        run: |
          NEW_VERSION=$(cat version)
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S.%6N')
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Commit of version changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add version version_log
          git commit -m "[${{ steps.new-version.outputs.new_version }}] <-- [${{ steps.old-version.outputs.old_version }}] [${{ steps.new-version.outputs.timestamp }}] ${{ steps.update-type.outputs.type }} up" || echo "No changes to commit"
          git push origin master  

      - name: Creating label with new version
        uses: actions/github-script@v6
        with:
          script: |
            const newVersion = "${{ steps.new-version.outputs.new_version }}";
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: [`${newVersion}`]
            });

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract labels for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/pipeline
          tags: |
            type=raw,value=v${{ steps.new-version.outputs.new_version }},enable=${{ job.status == 'success' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/pipeline
          readme-filepath: README.md

      - name: Add dockerhub label to PR
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['dockerhub']
              })
            } catch (error) {
              console.log('Error adding label:', error)
            }
